name: AutomaticBuild

on:
  push:
    branches: [ master ] #Everytime master branch is updated
    # paths: ['.github/workflows/*',  'src/*'] #only when these files are modifed
  pull_request:
    branches: [ master ] #for every pull request going to master
    # paths: ['.github/workflows/*', 'src/*'] #only when these files are modifed

jobs:

  makerelease:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.create_release.outputs.upload_url }}
      version: 0.0.${{ github.run_number  }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 0.0.${{ github.run_number  }}
          release_name: Curcuma 0.0.${{ github.run_number }}
          draft: false
          prerelease: true

  linux_20:
    needs: [makerelease]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: liblapacke-dev libatlas-base-dev libopenblas-dev libblas-dev liblapack-dev
        version: 1.0
    - name: Update Modules and Build
      run: sh scripts/build_unix_github.sh

    - name: Deploy
      run: sh scripts/deploy_unix_github_20_04.sh

    - name: Upload Release Asset
      id: upload-release-asset-20-04
      uses: actions/upload-release-asset@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.makerelease.outputs.url }}
        asset_path: ./package/curcuma-nightly-x86_64.AppImage
        asset_name: curcuma-nightly-${{ needs.makerelease.outputs.version }}-20_04-x86_64-Linux.AppImage
        asset_content_type: application/zip

  windows:
    needs: [makerelease]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Set up MinGW
        uses: e-t-l/setup-mingw@patch-1
        with:
            platform: x64

      - name: Update Modules and Build
        run: scripts/build_windows.bat
        


      

